version: 2

setup: &setup
  steps:
    - checkout
    - run: sudo apt update
    - run: sudo docker-php-ext-install zip
    - restore_cache:
        keys:
          - composer-dependencies-{{ checksum "composer.json" }}
    - run:
        name: Install Dependencies
        command: composer install -n --prefer-dist
    - save_cache:
        key: composer-dependencies-{{ checksum "composer.json" }}
        paths:
          - ./vendor
    - run:
        name: Run Tests
        command: ./vendor/bin/phpunit

jobs:
  php70:
    docker:
      - image: circleci/php:7.0
    <<: *setup

  php71:
    docker:
      - image: circleci/php:7.1
    <<: *setup

  php72:
    docker:
      - image: circleci/php:7.2
    <<: *setup

  php73:
    docker:
      - image: circleci/php:7.3
    <<: *setup

workflows:
  version: 2
  setup-and-test:
    jobs:
      - php70
      - php71
      - php72
      - php73
